// automatically generated by the FlatBuffers compiler, do not modify

package com.lion.flatbuffers;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class FbEsTapAPICommodity extends Table {
  public static FbEsTapAPICommodity getRootAsFbEsTapAPICommodity(ByteBuffer _bb) { return getRootAsFbEsTapAPICommodity(_bb, new FbEsTapAPICommodity()); }
  public static FbEsTapAPICommodity getRootAsFbEsTapAPICommodity(ByteBuffer _bb, FbEsTapAPICommodity obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public FbEsTapAPICommodity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String ExchangeNo() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer ExchangeNoAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public byte CommodityType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String CommodityNo() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer CommodityNoAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }

  public static int createFbEsTapAPICommodity(FlatBufferBuilder builder,
      int ExchangeNoOffset,
      byte CommodityType,
      int CommodityNoOffset) {
    builder.startObject(3);
    FbEsTapAPICommodity.addCommodityNo(builder, CommodityNoOffset);
    FbEsTapAPICommodity.addExchangeNo(builder, ExchangeNoOffset);
    FbEsTapAPICommodity.addCommodityType(builder, CommodityType);
    return FbEsTapAPICommodity.endFbEsTapAPICommodity(builder);
  }

  public static void startFbEsTapAPICommodity(FlatBufferBuilder builder) { builder.startObject(3); }
  public static void addExchangeNo(FlatBufferBuilder builder, int ExchangeNoOffset) { builder.addOffset(0, ExchangeNoOffset, 0); }
  public static void addCommodityType(FlatBufferBuilder builder, byte CommodityType) { builder.addByte(1, CommodityType, 0); }
  public static void addCommodityNo(FlatBufferBuilder builder, int CommodityNoOffset) { builder.addOffset(2, CommodityNoOffset, 0); }
  public static int endFbEsTapAPICommodity(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

